"""
Pydantic schemas for LLM inputs and structured outputs.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class LLMResponse(BaseModel):
    """Normalized provider-independent LLM response."""
    provider: str = Field(..., description="Name of the responding LLM provider (e.g., 'groq', 'gemini', 'mock')")
    model: str = Field(..., description="Model identifier used")
    content: str = Field(..., description="Raw text or JSON content generated by LLM")
    usage: Optional[Dict[str, Any]] = Field(default=None, description="Token usage statistics if provided")


class ProposedHypothesis(BaseModel):
    """A candidate misconception hypothesis proposed by the LLM."""
    id: str = Field(..., description="Machine-readable misconception ID")
    label: str = Field(..., description="Short title describing the misconception")
    initial_probability: float = Field(default=0.33, description="LLM-suggested initial probability prior to engine normalization")
    predicted_wrong_options: List[str] = Field(default_factory=list, description="Distractor options student would pick under this misconception")
    reason: str = Field(..., description="Why this misconception is suspected given the student error")


class HypothesisProposalResponse(BaseModel):
    """Container for candidate hypotheses generated by LLM."""
    hypotheses: List[ProposedHypothesis] = Field(..., min_length=1, max_length=5)


class VideoSnippet(BaseModel):
    title: str = Field(..., description="Educational clip title")
    youtube_video_id: str = Field(..., description="YouTube video ID")
    start_seconds: int = Field(default=0, description="Start timestamp in seconds")
    end_seconds: int = Field(default=120, description="End timestamp in seconds")
    concept_summary: str = Field(..., description="Key concept addressed in this segment")


class RemediationResponse(BaseModel):
    """Targeted remediation generated for a confirmed misconception."""
    misconception_id: str = Field(..., description="ID of the addressed misconception")
    remediation_title: Optional[str] = Field(default=None, description="Engaging, encouraging title")
    remediation_text: str = Field(..., description="Clear explanation of the conceptual misunderstanding and the correct principle")
    differences: Optional[list[dict[str, str]]] = Field(default=None, description="List of dicts with 'misconception_aspect' and 'reality_aspect'")
    example: Optional[str] = Field(default=None, description="Intuitive physical analogy or counter-example")
    key_takeaway: Optional[str] = Field(default=None, description="Memorable summary rule")
    check_for_understanding: Optional[str] = Field(default=None, description="Reflective question prompting self-check")
    grounded_source: Optional[str] = Field(default=None, description="Source citation or textbook reference if applicable")
    feynman_explanation: Optional[str] = Field(default=None, description="Feynman-style simplified breakdown without jargon")
    visual_artifact_svg: Optional[str] = Field(default=None, description="Self-contained SVG visual artifact")
    video_snippet: Optional[VideoSnippet] = Field(default=None, description="Curated educational video segment")


class SelfConsistencyResponse(BaseModel):
    """
    Simulation result: an LLM roleplaying a student holding a specific misconception
    predicts which option that student would choose.
    """
    predicted_option: str = Field(..., description="Option letter ('A', 'B', 'C', 'D') that the simulated student picks")
    reasoning_summary: str = Field(..., description="Concise rationale for why the misconception produces this choice")
    confidence: float = Field(default=0.8, ge=0.0, le=1.0, description="Confidence of the simulated student")
